### ISSUE TITLE
Write_XYZ uses pre-defined species

### ISSUE THREAD

**Issue by Fratorhe** [SamTov/MDSuite#11]
Hello Sam, 

I was reading the code and in file Meta_functions line 24, the species are pre-defined, which I guess can provoke in the future.
I am not sure if the species should be an input to the function, or the function can retrieve them from the array. 
It is a very minor issue, but better to get it fixed now. 

Regards, 
Francisco

**Comment by SamTov** [comment]
This is an old function I wrote when testing the unwrapping capabilities. I will make it a class method instead so it can access all of the attributes.

**Comment by SamTov** [comment]
It is now a class method. I will add an example to the tutorial to see how it can be used. I am closing this issue.
