### ISSUE TITLE
TypeError in  Classes.py

### ISSUE THREAD

**Issue by Fratorhe** [SamTov/MDSuite#18]
Hi Sam,

After your commit "Fix hard coded conductivity charge assignment and add periodic table functionality" (fa8862a607301412043a850cb299f01447039079). There is a TypeError: 'int' object is not subscriptable in:
`diffusion_array.append(_diffusion_coefficients["Singular"][element] *
                                       abs(self.species[element]['charge'][0]) *
                                       (len(self.species[element]['indices']) / self.number_of_atoms))
`

**Comment by SamTov** [comment]
I will fix this today
