### ISSUE TITLE
Move all global variables to data file.

### ISSUE THREAD

**Issue by SamTov** [SamTov/MDSuite#229]
**What feature would you like to see added?**
In line with the discussion in PR #228, we should move all global variables in the file loading to a data file. 

**Describe how this feature would improve the code**
It will prevent any issues with global variables. This is particularly important when change are made to them during some analysis, as takes place in the file loading.

**Describe how this feature would work/possible implementations**
Move the dictionary variables to a JSON file and load them when they are required, i.e., in a class __init__.

**Comment by PythonFZ** [comment]
As a possible alternative or addition we can use dataclasses.
An example for the units could be:

from dataclasses import dataclass

```py
from dataclasses import dataclass

@dataclass(frozen=True)
class Units:
    pressure: float = 1.23456
    length: float = 1.1234656
    
   def gk_prefactor(self):
       return self.pressure ** 2 * self.length ** 3 + ...
```

They can be read from a json file or written to a json file easily.

**Comment by PythonFZ** [comment]
I think this is resolved? @SamTov
