### ISSUE TITLE
Add checks for the hdf5 functions

### ISSUE THREAD

**Issue by SamTov** [SamTov/MDSuite#7]
If a hdf5 database is to be generated and it already exists, it will throw errors. This should be replaced with simply performing the calculation with the available data and then leaving a message.

**Comment by Fratorhe** [comment]
For me, it gives the error when trying to create a new folder and it already exists. I added this piece of code in the thermal conductivity case which may be a simple solution (maybe not the most elegant).
        try:
            os.mkdir('{0}/{1}'.format(self.filepath, self.analysis_name))
        except FileExistsError:
            pass

**Comment by SamTov** [comment]
This is exactly what is needed, if you check the comments I made on the pull request, perhaps we can merge the Methods.py commits and wait until we have spoken about the other parts.
